#! /bin/sh
# $Id: confwrapper.sub,v 1.2.2.1 2003/12/27 17:15:20 aida_s Exp $

case "$1" in
  filter)
  envname="$2"
  shift
  shift
  for p in "$@"; do
    case "$p" in
      *" "*|*" 	"*|*"'"*|*'"'*)
      echo 'confwrapper: warning: removing "'"$p"'" from '"$envname" >&2
      ;;
      *) args="$args $p" ;;
    esac
  done
  cat << EOF
$args
EOF
  ;;

  *)
  echo "confwrapper.sub: Bad argument" >&2
  exit 1
  ;;
esac
