#! /bin/sh
# $Id: confwrapper,v 1.4.2.3 2004/04/26 23:15:17 aida_s Exp $
# vim: set sw=2 ts=8:

set -e
case "$1" in
  run)
  shift
  if test ! -r cwenv.sh; then
    make cwenv.sh
  fi
  . cwenv.sh
  if test -r cwlocal.sh; then
    . cwlocal.sh
  fi
  export CPPFLAGS CC CFLAGS
  echo "CPPFLAGS=\"$CPPFLAGS\""
  echo "CC=\"$CC\""
  echo "CFLAGS=\"$CFLAGS\""
  echo "$@"
  exec "$@"
  ;;

  mkenv)
  envname="$2"
  shift
  shift
  for p in "$@"; do
    case "$p" in
      *" "*|*" 	"*|*"'"*|*'"'*)
      echo 'confwrapper: warning: removing "'"$p"'" from '"$envname" >&2
      ;;
      *) args=$args${args+" "}$p ;;
    esac
  done
  cat << EOF
$envname="$args"
EOF
  ;;

  *)
  echo "confwrapper.sub: Bad argument" >&2
  exit 1
  ;;
esac
